services:
  hc: 
    hostname: hadoop_container_v2
    image: hadoop-build
    # ports:
    #   - 9870:9870       # namenode port
    #   - 8088:8088       # resourcemanager port
    #   - 19888:19888     # mapreduce jobHistory server
    #   - 9090:9090       # webappproxy server
    volumes:
      - 
